ENDPOINT_SCOPE = '/the-game'
ACTIVE_GAMES_TABLE = 'the_game_active_games'
LEADER_BOARD_TABLE = 'the_game_leader_board'


MAX_CARDS = 100
ON_FIRE_CARDS = [22, 33, 44, 55, 66, 77]
ON_FIRE_LIFE = 1
N_ASCENDING_PILES = 2
N_DESCENDING_PILES = 2
