from games.catan.models.board.board import Board
from games.catan.models.port import Port, PortType
from games.catan.models.board.generators import start_position_generator, intersections_generator

CLASSIC_BOARD = Board(
    n_wood=4,
    n_wheat=4,
    n_sheep=4,
    n_brick=3,
    n_stone=3,
    n_desert=1,
    start_positions=start_position_generator(3, 3, 3),
    number_list=[5, 2, 6, 3, 8, 10, 9, 12, 11, 4, 8, 10, 9, 4, 5, 6, 3, 11],
    ports=[
        Port(port_type=PortType.Sheep, intersections=({-18, -1, 0}, {-18, -17, 0})),
        Port(port_type=PortType.General, intersections=({-16, -15, 2}, {-15, -14, 2})),
        Port(port_type=PortType.Brick, intersections=({-14, -13, 3}, {-13, 3, 4})),
        Port(port_type=PortType.General, intersections=({-12, -11, 4}, {-11, 4, 5})),
        Port(port_type=PortType.Wood, intersections=({-10, -9, 6}, {-9, -8, 6})),
        Port(port_type=PortType.Stone, intersections=({-8, -7, 7}, {-7, 7, 8})),
        Port(port_type=PortType.General, intersections=({-7, -6, 8}, {-6, -5, 8})),
        Port(port_type=PortType.Wheat, intersections=({-5, 8, 9}, {-5, -4, 9})),
        Port(port_type=PortType.General, intersections=({-3, -2, 10}, {-2, 10, 11})),
    ],
    intersections=intersections_generator(3, 3, 3),
    n_knight=14,
    n_monopoly=2,
    n_materials=2,
    n_roads=2,
    n_point=5,
    n_per_player_cities=8,
    n_per_player_roads=30,
    n_per_player_settlements=10,
)

EXTENDED_3_4_4_BOARD = Board(
    n_wood=6,
    n_wheat=6,
    n_sheep=6,
    n_brick=5,
    n_stone=5,
    n_desert=2,
    start_positions=start_position_generator(3, 4, 4),
    number_list=[2, 5, 4, 6, 3, 9, 8, 11, 11, 10, 6, 3, 8, 4, 8, 10, 11, 12, 10, 5, 4, 9, 5, 9, 12, 3, 2, 6],
    ports=[
        Port(port_type=PortType.General, intersections=({-22, -21, 0}, {-22, -1, 0})),
        Port(port_type=PortType.Wood, intersections=({-21, -20, 1}, {-20, 1, 2})),
        Port(port_type=PortType.General, intersections=({-19, -18, 2}, {-18, 2, 3})),
        Port(port_type=PortType.Brick, intersections=({-17, 3, 4}, {-17, -16, 4})),
        Port(port_type=PortType.General, intersections=({-16, -15, 5}, {-15, -14, 5})),
        Port(port_type=PortType.General, intersections=({-13, -12, 7}, {-12, 7, 8})),
        Port(port_type=PortType.Sheep, intersections=({-10, 8, 9}, {-10, -9, 9})),
        Port(port_type=PortType.General, intersections=({-9, -8, 10}, {-8, -7, 10})),
        Port(port_type=PortType.Stone, intersections=({-6, -5, 12}, {-5, 12, 13})),
        Port(port_type=PortType.Sheep, intersections=({-3, 13, 14}, {-3, -2, 14})),
        Port(port_type=PortType.Wheat, intersections=({-2, 14, 15}, {-2, -1, 15})),
    ],
    intersections=intersections_generator(3, 4, 4),
    n_knight=20,
    n_monopoly=3,
    n_materials=3,
    n_roads=3,
    n_point=5,
    n_per_player_cities=8,
    n_per_player_roads=30,
    n_per_player_settlements=10,
)
